#!/bin/bash

# Generate GitHub Secrets for CI/CD
# This script generates secure values for GitHub Actions secrets

echo "=========================================="
echo "GitHub Secrets Generator for MyERP"
echo "=========================================="
echo ""
echo "Copy these values to GitHub Repository Settings → Secrets and variables → Actions"
echo ""
echo "=========================================="
echo "REQUIRED SECRETS FOR CI"
echo "=========================================="
echo ""

# Generate JWT_SECRET
JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
echo "1. JWT_SECRET"
echo "   Value: $JWT_SECRET"
echo "   Description: Secret key for JWT token signing (minimum 32 characters)"
echo ""

echo "2. JWT_EXPIRES_IN"
echo "   Value: 7d"
echo "   Description: JWT token expiration time"
echo ""

echo "3. NEXT_PUBLIC_API_URL"
echo "   Value: https://api.yourdomain.com/api"
echo "   Description: Backend API URL for frontend builds"
echo "   ⚠️  Update with your actual API URL"
echo ""

echo "=========================================="
echo "OPTIONAL SECRETS FOR CD (Deployment)"
echo "=========================================="
echo ""
echo "Add these only if you're setting up deployment:"
echo ""
echo "4. BACKEND_URL"
echo "   Value: https://api.yourdomain.com"
echo ""
echo "5. FRONTEND_URL"
echo "   Value: https://yourdomain.com"
echo ""
echo "For SSH Deployment:"
echo "6. HOST - Your server hostname"
echo "7. USERNAME - SSH username"
echo "8. SSH_KEY - SSH private key"
echo ""
echo "For Vercel Deployment:"
echo "9. VERCEL_TOKEN - Vercel API token"
echo "10. VERCEL_ORG_ID - Vercel organization ID"
echo "11. VERCEL_PROJECT_ID - Vercel project ID"
echo ""
echo "=========================================="
echo "QUICK COPY COMMANDS"
echo "=========================================="
echo ""
echo "# Copy JWT_SECRET to clipboard (macOS):"
echo "echo '$JWT_SECRET' | pbcopy"
echo ""
echo "# Copy JWT_SECRET to clipboard (Linux):"
echo "echo '$JWT_SECRET' | xclip -selection clipboard"
echo ""
echo "# Copy JWT_SECRET to clipboard (Windows PowerShell):"
echo "echo '$JWT_SECRET' | Set-Clipboard"
echo ""
echo "=========================================="
echo "NEXT STEPS"
echo "=========================================="
echo "1. Go to: https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Add each secret with the values above"
echo "4. Push a change to trigger workflows"
echo ""
